apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      containers:
      - image: gchangdckr/dsodemo:v5
        name: dsodemo
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
      - name: regcred
status: {}
